- name: Check last patch date
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: check last patch for RedHat
      command: bash -c 'dnf history |grep "update" | egrep "2024-12|2025" | head -1'
      register: last_patch
      when: ansible_distribution == "RedHat"

    - name: set variable for RedHat
      set_fact:
        LAST_PATCH_OUT: "{{ last_patch.stdout_lines }}"
      when: ansible_distribution == "RedHat"


    - name: check last patch SLES
      command: bash -c 'fgrep "\'update\'" /var/log/zypp/history | tail -1'
      register: last_patch
      when: ansible_distribution == "SLES_SAP"

    - name: set variable for SLES
      set_fact:
        LAST_PATCH_OUT: "{{ last_patch.stdout_lines }}"
      when: ansible_distribution == "SLES_SAP"


    - name: check last reboot
      shell: last reboot | grep wtmp | head -1
      register: last_reboot

    - name: set variable for last reboot
      set_fact:
        LAST_REBOOT_OUT: "{{ last_reboot.stdout_lines }}"

    - name: print state
      debug:
        msg: "ITEM: {{ inventory_hostname }} last patch: {{ LAST_PATCH_OUT }}  last reboot {{ LAST_REBOOT_OUT }}"
