- hosts: all
  become: yes
  gather_facts: no
  ignore_errors: true
  vars:

  tasks:

  - name: read file list
    command: bash -c 'ls /tmp'
    register: cmdoutput

  - name: print file list
    debug:
      msg: "{{ cmdoutput.stdout_lines }}\n"
